# Monitor
monitor=eDP-1,3200x2000@165, 0x0, 1.6

# Programs
$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun

# Autostart
exec-once = waybar
exec-once = swaync
exec-once = hyprpaper
exec-once = hypridle
exec-once = $HOME/.local/bin/spotify-nowplaying

# Environment
env = XCURSOR_SIZE,24
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

# General
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 4


    col.active_border = rgb(000000)
    col.inactive_border = rgb(00334d)


    allow_tearing = false
}

# Decoration
decoration {
    active_opacity = 0.95
    inactive_opacity = 0.90
    rounding = 8

    blur {
        enabled = true
        size = 3
        passes = 2
    }

    shadow {
        enabled = true
        range = 4
        render_power = 3
    }
}

# Animations
animations {
    enabled = true

    bezier = easeOut, 0.05, 0.9, 0.1, 1.0

    animation = windows, 1, 5, easeOut
    animation = windowsOut, 1, 5, easeOut
    animation = fade, 1, 5, easeOut
    animation = workspaces, 1, 5, easeOut
}

# Layout
dwindle {
    preserve_split = true
}

# Input
input {
    kb_layout = us
    follow_mouse = 1

    touchpad {
        natural_scroll = true
    }
}

# Keybinds
$mainMod = SUPER

# Terminal
bind = SUPER, Q, exec, $terminal

# Application launcher
bind = SUPER, R, exec, $menu
bind = SUPER, F, exec, vivaldi
bind = SUPER, E, exec, $fileManager
bind = SUPER, A, exec, cursor
bind = SUPER, S, exec, spotify


# Close window
bind = SUPER, C, killactive

# Reload Hyprland

# Exit Hyprland

# Move focus
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Move windows
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# Move window to workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

# Mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Brightness
bindel = , XF86MonBrightnessUp, exec, brightnessctl -d intel_backlight set 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl -d intel_backlight set 5%-

# Volume
bindel = , XF86AudioRaiseVolume, exec, pamixer -i 5
bindel = , XF86AudioLowerVolume, exec, pamixer -d 5
bindl = , XF86AudioMute, exec, pamixer -t

# Media
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPrev, exec, playerctl previous
bindl = , Home, exec, playerctl play-pause
bindl = , Page_Up, exec, playerctl previous
bindl = , Page_Down, exec, playerctl next
